language: java

#command to install dependencies
install:
  - "mvn clean install"

#command to deploy
deploy:
  provider: gae
  project: pactedeschiens-2
  keyfile: pactedeschiens 2-56c196f1588f.json
